<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @package \Repository
 *
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @param $slug
     * @return mixed
     */
    public function retrieveBySlug($slug)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.slug = :slug')
            ->orderBy('c.categoryName','ASC')
            ->getQuery();

        $query->setParameter('slug',$slug);

        return $query->getResult();
    }

    /**
     * @return mixed
     */
    public function retrieveFirst()
    {
        $query = $this->find('1');

        return $query;
    }

    /**
     * @return array
     */
    public function retrieveAll()
    {
        $query = $this->findAll();

        return $query;
    }
}
