app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#genj_faq:
    #resource: "@GenjFaqBundle/Resources/config/routing.yml"
